# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               HarishV's Blog
tagline:             'Life & Code'
description:        'Computer Engineering Student'
url:                harishv7.github.io/blog
baseurl:             /blog
paginate:            5

# About/contact
author:
  name:              Harish V
  url:               https://harishv7.wordpress.com
  email:             harish207@live.com

# Custom vars
version:             2.5.0
